#!/bin/sh /etc/rc.common

START=99
STOP=15
USE_PROCD=1

NAME=teamtalk
PROG=/usr/bin/teamtalkd

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    procd_stop_instance
}

reload_service() {
    stop
    start
}
